name: cd

on:
  push:
    branches:
      - main
      - developer

env: 
  AWS_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/developer'

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: terraform init
      id: init
      run: terraform init
    
    - name: select production workspace
      if: github.ref == 'refs/heads/main'
      run: terraform workspace select production || terraform workspace new production
    
    - name: select dev workspace
      if: github.ref == 'refs/heads/developer'
      run: terraform workspace select development || terraform workspace new development
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -lock=false

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -lock=false